server:
  port: 7777

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        enabled: true
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/agd/client-service/api/**
          filters:
            - AuthenticationFilter
        - id: client-service-mocks
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/agd/client-service/mocks/**


        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/agd/notification-service/**


        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/agd/security-service/**


        - id: relaunch-service
          uri: lb://RELAUNCH-SERVICE
          predicates:
            - Path=/agd/relaunch-service/**


        - id: configuration-service
          uri: lb://CONFIGURATION-SERVICE
          predicates:
            - Path=/agd/configuration-service/**


        - id: contact-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/agd/contact-service/**
            

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/agd/payment-service/payment/**
          filters:
            - AuthenticationFilter
        - id: payment-service-cmi
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/agd/payment-service/cmi/**



        - id: administrateur-service-admin
          uri: lb://ADMINISTRATEUR-SERVICE
          predicates:
            - Path=/agd/administrateur-service/admin/**
          filters:
              - name: AuthenticationFilter
              - name: AuthenticationAdminFilter
        - id: administrateur-service-agent
          uri: lb://ADMINISTRATEUR-SERVICE
          predicates:
            - Path=/agd/administrateur-service/agent/**
          filters:
            - name: AuthenticationFilter
            - name: AuthenticationAgentFilter
        - id: administrateur-service-api
          uri: lb://ADMINISTRATEUR-SERVICE
          predicates:
            - Path=/agd/administrateur-service/api/**
          filters:
            - AuthenticationFilter


        - id: rdv-service
          uri: lb://RDV-SERVICE
          predicates:
            - Path=/agd/rdv-service/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Access-Control-Allow-Origin"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka






