server:
  port: 7777

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        enabled: true
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/agd/client-service/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/agd/notification-service/**
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/agd/security-service/**
        - id: relaunch-service
          uri: lb://RELAUNCH-SERVICE
          predicates:
            - Path=/agd/relaunch-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Access-Control-Allow-Origin"
            allowCredentials: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka




