INSERT INTO bd_config.param (param_name, param_value) VALUES
('SIMILARITY', '80'),
('NBR_GENERATION', '5'),
('NEW_DATE_GENERATION','30'),
('DATE_EXPIRATION', '15'),
('MAX_ATTEMPTS', '3'),
('OTP_LENGTH', '8'),
('SECRET_KEY_BYTES', 'VV3KOX7UQJ4KYAKOHMZPPH3US4CJIMH6F3ZKNB5C2OOBQ6V2KIYHM27Q'),
('SECRET_KEY_TOKEN', 'VV3KOX7UQJ4KYAKOHMZPPH3US4CJIMH6F3ZKNB5C2OOBQ6V2KIYHM27Q'),
('TOKEN_VALIDITY_PARAM','3600'),
('RELAUNCH_SCHEDU', '09:00');